GolfzonTech-WorkTalk/WorkTalk-BE

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/WorktalkApplication.java
- src/main/java/com/golfzonTech4/worktalk/config/CorsConfig.java
- src/main/java/com/golfzonTech4/worktalk/config/SecurityConfig.java
- src/main/java/com/golfzonTech4/worktalk/controller/AuthController.java
- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Member.java
- src/main/java/com/golfzonTech4/worktalk/domain/MemberType.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/LoginDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberMailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/TokenDto.java
- src/main/java/com/golfzonTech4/worktalk/exception/DuplicateMemberException.java
- src/main/java/com/golfzonTech4/worktalk/exception/NotFoundMemberException.java
- src/main/java/com/golfzonTech4/worktalk/jwt/JwtAccessDeniedHandler.java
- src/main/java/com/golfzonTech4/worktalk/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/com/golfzonTech4/worktalk/jwt/JwtFilter.java
- src/main/java/com/golfzonTech4/worktalk/jwt/JwtSecurityConfig.java
- src/main/java/com/golfzonTech4/worktalk/jwt/TokenProvider.java
- src/main/java/com/golfzonTech4/worktalk/repository/MemberRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/CustomUserDetailsService.java
- src/main/java/com/golfzonTech4/worktalk/service/MailService.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
- src/main/java/com/golfzonTech4/worktalk/util/SecurityUtil.java
1. 회원가입 기능 구현
- SMTP를 이용한 메일 인증 기능 구현
- 중복 메일, 회원명 검증 기능 구현
2. 로그인 기능 구현
- 스프링 시큐리티 + JWT를 이용한 로그인 기능 구현
> [2022-11-23 1st PR]  회원가입 및 로그인  기능 구현

- src/main/java/com/golfzonTech4/worktalk/jwt/JwtFilter.java
> Fix login error(adding postman code)

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 예약 NOSHOW회원 대상 저장 중 중복 제거를 위해 ArrayList 대신  HashSet을 사용
> [2022-11-27 1st PR] 예약 기능 개선

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/config/EmailConfig.java
- src/main/java/com/golfzonTech4/worktalk/controller/MailController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/domain/BookDate.java
- src/main/java/com/golfzonTech4/worktalk/domain/Mileage.java
- src/main/java/com/golfzonTech4/worktalk/domain/MyIamport.java
- src/main/java/com/golfzonTech4/worktalk/domain/Pay.java
- src/main/java/com/golfzonTech4/worktalk/domain/PaymentStatus.java
- src/main/java/com/golfzonTech4/worktalk/domain/Reservation.java
- src/main/java/com/golfzonTech4/worktalk/domain/ReserveStatus.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayInsertDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayScheduleDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayWebhookDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveSimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MailService.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 결제 기능 추가 (일반 결제, 예약 결제)
2. 예약 기능 개선 (예약 취소 후 결제 취소)
3. 메일 기능 추가(예약 결제 실패 시 메일 자동 발송)
> [2022-11-30 1st PR] 결제 기능 및 예약 기능 개선

- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Mileage.java
- src/main/java/com/golfzonTech4/worktalk/domain/Mileage_status.java
- src/main/java/com/golfzonTech4/worktalk/dto/mileage/MileageDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/mileage/MileageFindDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
> [2022-12-01 1st PR] 마일리지 기능 추가

- build.gradle
1. AWS RDS 사용을 위한 DB 변경 (Oracle=> Postgresql)
> [2022-12-01 4th PR] DB 변경

- src/test/java/com/golfzonTech4/worktalk/WorktalkApplicationTests.java
> comment out test

- .travis.yml
> [2022-12-02 1st PR] .travis.yml 추가

- .travis.yml
빌드 에러 방지를 위한 
before_install:
chmod +x gradlew 코드 추가
> [2022-12-02 2ndPR] .travis.yml 수정

- .travis.yml
Travis CI 와 AWS S3 연동을 한 코드 추가
> [2022-12-02 3rd PR] .travis.yml  s3 관련 설정 추가

- .travis.yml
> [2022-12-02 4rd PR] .travis.yml s3 관련 설정 추가 (브랜치 설정 관련)

- .travis.yml
> [2022-12-02 4th PR] .travis.yml s3 관련 설정 추가 

- .travis.yml
- appspec.yml
- scripts/deploy.sh
Creating deploy.sh and updating .travis.yml, appspec.yml
> [2022-12-02 6th PR] .travis.yml, deploy.sh, appspec.yml codedeploy 관련 설정 추가 

- .travis.yml
- appspec.yml
- scripts/deploy.sh
배포가 안되는 문제를 해결하기 위해 appspec.yml의 destination 경로 수정
> [2022-12-02 7th PR] .travis.yml, deploy.sh, appspec.yml codedeploy 관련 설정 추가 

- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/domain/BookDate.java
- src/main/java/com/golfzonTech4/worktalk/domain/Pay.java
- src/main/java/com/golfzonTech4/worktalk/dto/mileage/MileageDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayInsertDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 마일리지 기능 추가
- 마일리지 사용, 적립, 취소(사용, 적립), 조회 기능 추가
2. 결제/예약 기능 업데이트
- 예약 ~ 결제 ~ 마일리지 간 기능 연동
- 예약 취소 시 결제 취소 및 마일리지 적립/사용 내역 취소 기능 추가
- 아임포트 웹훅을 이용하여 예약 결제 실행 시 해당 결제 정보 자동 저장 및 예약 내역 중 결제상태 변경
> [2022-12-03 1st PR] 마일리지 기능 추가, 결제/ 예약 기능 업데이트

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/config/AwsConfig.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Space.java
- src/main/java/com/golfzonTech4/worktalk/domain/SpaceImg.java
- src/main/java/com/golfzonTech4/worktalk/repository/SpaceImgRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/AwsS3Service.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceImgService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 사무공간엔티티 이미지 컬럼 삭제
2. 사무공간이미지 테이블명 수정
3. S3 설정 추가
> 사무공간 이미지관련 테이블 수정 및 S3 설정 추가

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/controller/MileageController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
컨트롤러 URL 수정 및 Build에러 관련 build.gradle 수정
> [2022-12-03 2nd PR] 컨트롤러 URL 수정 및 Build에러 관련 build.gradle 수정

- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Reservation.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayOrderSearch.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PaySearchDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PaySimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveOrderSearch.java
- src/main/java/com/golfzonTech4/worktalk/repository/ListResult.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 조회 기능 추가
- 사용자/ 호스트 예약 리스트 조회(소팅, 조건검색, 페이징)
- 사용자/ 호스트 결제 리스트 조회(소팅, 조건검색, 페이징)
2. 예약 이용 종료 기능 추가 : 사용 시간이 지난 예약건에 대하여 호스트가 상태를 종료로 변경
> [2022-12-04 1st PR] 조회 기능 추가 및 예약 이용 종료 기능 추가

- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
1. Reservation Controller 주석추가
> [2022-12-05 1st PR] 주석 추가

- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCommentController.java
- src/main/java/com/golfzonTech4/worktalk/controller/QnaController.java
- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Space.java
- src/main/java/com/golfzonTech4/worktalk/domain/SpaceImg.java
- src/main/java/com/golfzonTech4/worktalk/dto/customercenter/CustomerCenterDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/customercenter/CustomerCenterUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceImgDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceInsertDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/CustomerCenterRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/SpaceRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/AwsS3Service.java
- src/main/java/com/golfzonTech4/worktalk/service/CustomerCenterService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 1대 1 문의 에러 수정 -> 구현 완료
2. 사무공간 이미지업로드 수정
> 1대1문의, space 이미지업로드 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/MileageController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/controller/UserController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Penalty.java
- src/main/java/com/golfzonTech4/worktalk/domain/PenaltyType.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PaySimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/penalty/PenaltyDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/ListResult.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/penalty/PenaltyRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/penalty/PenaltyRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/penalty/PenaltyRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/PenaltyService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 조회 기능 수정(결제, 마일리지, 예약)
2. 회원 탈퇴, 수정 기능 추가
> [2022-12-05 2ndPR] 조회 기능 수정

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 빌드 시 ~-plain 파일 생성 방지를 위한 build.gradle 상의 설정 추가
2. 예약 기능 관련 매 시간 30분 마다 노쇼 처리를 위한 로직 추가
> [2022-12-06 2nd PR] 빌드 관련 설정 변경 및 예약 기능 개선

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 기존 노쇼 조회 매서드가 30초 단위로 작동되던 코드를 30분 마다 돌아가게 수정
> [2022-12-06 4th PR] 예약 기능 수정

- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
> [2022-12-08 2nd PR -1] 페널티 컨트롤러 URL

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberSerachDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
- src/main/java/com/golfzonTech4/worktalk/service/PenaltyService.java
1. 컨트롤러 주소 수정
2. 페널티 리스트 소팅 기능 추가
3. 예약 조회 기능 쿼리 수정
> [2022-12-08 4th PR] 컨트롤러 수정, 페널티 소팅 기능 추가, 예약 조회 기능 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayOrderSearch.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveOrderSearch.java
1. GET 방식에서 @RequestBody 어노테이션을 @RequestParam으로 변경
> [2022-12-08 5thd PR] 컨트롤러 파라미터 어노테이션 변경

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
1. GET 방식에서 @RequestParam 어노테이션을 @ModelAttribure으로 변경
> [2022-12-08 5thd PR-2] 컨트롤러 파라미터 어노테이션 변경

- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveCheckDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/PenaltyService.java
> [2022-12-08 6th PR] DTO 어노테이션 수정

- src/main/java/com/golfzonTech4/worktalk/controller/PenaltyController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 마일리지 총액 조회 에러 수정
2. 예약 내역 조회 수정
3. 회원 리스트 조회 에러 수정
> [2022-12-08 9th PR] 에러 수정

- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveTempDto.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempReservationService.java
> [2022-12-08 10th PR] 에러 수정

- src/main/java/com/golfzonTech4/worktalk/domain/BookDate.java
1. reservation ~ BookDate ~ validDate매서드에 오류 수정
> [2022-12-08 11th PR] reservation 매서드 수정

- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
1. 예약 컨트롤러 파라미터 어노테이션 수정 (RequestBody -> ModelAttribute)
> [2022-12-09 1st PR] 예약 컨트롤러 수정

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-09 2nd PR] 예약 서비스 수정

- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Reservation.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PaySimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveOrderSearch.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveSimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 예약 조건 조회 수정
2. 결제 로직 수정 => 선결제 중 잔금 처리 시 예약 결제 상태 변경 로직 추가
> [2022-12-09 3rd PR] 예약 조건 조회 수정, 결제 로직 수정

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/config/SwaggerConfig.java
1. swagger 설정 및 build.gradle 수정
> swagger 설정

- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/domain/SpaceImg.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceMainDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/AwsS3Service.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceImgService.java
1. 메인화면의 space 출력정보에 상세주소 추가
2. Aws s3 delete 메소드 추가
> 메인화면의 space정보 수정, Aws s3 delete메소드 추가

- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceMainDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceSearchDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 스페이스컨트롤러-spaceCreate메서드에 consumes 추가
2. 메인 search 쿼리문 날짜 시간 검색 로직 추가
> spaceController, search쿼리문 수정

- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCenterController.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
1. DeleteMapping -> GetMapping으로 수정(테스트)
> CustomerCenterController delete메서드 수정

- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCenterController.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
1. CustomerCenterController GetMapping을 DeleteMapping으로 원복
2. search 기능 수정
> CustomerCenterController delete메서드 원복, search 기능 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MailService.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempReservationService.java
1. 마일리지 조회 오류 해결
2. 예약 동시성 문제 개선: 예약 전 중복 확인 매서드 추가, Repository ~ save ~ pessimistic lock 추가
> [2022-12-12 1st PR] 마일리지 조회 오류 fix 및 예약 동시성 문제 개선

- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceSearchDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 사무공간 상세페이지에서 이미지리스트 받아오게 수정
> 사무공간 상세페이지 수정

- scripts/deploy.sh
> [2022-12-12 2nd PR] 배포 관련 설정 수정

- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 리뷰 평점 소수점 첫째자리까지 출력되게 수정
2. 메인페이지 검색 기능 오류 수정
> Review 평점 수정, Main Search기능 수정

- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveSimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/temp/TempReservationRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempReservationService.java
1. 예약 리스트 조회 시 리뷰 여부 출력
2. 예약 가능 공간 조회 시 임시 예약 테이블에서 입력시간이 5분 초과된 데이터 삭제 로직 추가
> [2022-12-14 1st PR] 예약 기능 개선 

- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceMainDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
1. 호스트 공간관리리스트 정보(승인상태) 추가
2. 사무공간상세페이지 호스트정보(tel) 추가
> 호스트 공간관리리스트 정보(승인상태) 추가, 사무공간상세페이지 호스트정보(tel) 추가

- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
> 세부공간 등록 컨트롤러 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
> [2022-12-14 2nd PR] 회원 컨트롤러 주소 변경

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
>  [2022-12-14 3rdPR] 회원 서비스 로직 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MainController.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceManageSortingDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 마스터 사무공간 관리 페이지 수정
- 페이징 추가
- 다중 소팅(사무공간 유형, 승인상태, 사무공간 등록순으로 정렬)
> 마스터 사무공간 관리페이지 페이징, 다중 소팅 조건 추가

- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/domain/CustomerComment.java
- src/main/java/com/golfzonTech4/worktalk/domain/Member.java
- src/main/java/com/golfzonTech4/worktalk/domain/QnaComment.java
- src/main/java/com/golfzonTech4/worktalk/domain/Review.java
- src/main/java/com/golfzonTech4/worktalk/domain/Room.java
- src/main/java/com/golfzonTech4/worktalk/domain/Space.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceImgService.java
1. 사무공간 이미지 삭제 API 구현
2. 엔티티 변경
- Member 테이블 Tel Null 허용
- QnA, CustomerCenter 답글 pk 추가
> 이미지삭제 로직 구현, 엔티티 변경

- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCommentController.java
- src/main/java/com/golfzonTech4/worktalk/controller/QnaCommentController.java
- src/main/java/com/golfzonTech4/worktalk/domain/CustomerComment.java
- src/main/java/com/golfzonTech4/worktalk/domain/QnaComment.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCommentRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaCommentRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/CustomerCommentService.java
- src/main/java/com/golfzonTech4/worktalk/service/QnaCommentService.java
1. 엔티티 변경으로 인한 service,repository,controller 수정
> 엔티티 변경으로 인한 service,repository,controller 수정

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/controller/KakaoController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Member.java
- src/main/java/com/golfzonTech4/worktalk/dto/member/KakaoProfileDto.java
- src/main/java/com/golfzonTech4/worktalk/service/KakaoJoinService.java
> 카카오 소셜로그인 추가

- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/room/RoomImgRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceImgRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
> space, room 수정(+이미지) 로직 구현

- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
1. SpaceController spaceUpdate url 수정
> SpaceController url 수정

- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Room.java
- src/main/java/com/golfzonTech4/worktalk/domain/RoomImg.java
- src/main/java/com/golfzonTech4/worktalk/domain/SpaceImg.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
1. 세부공간 이미지 삭제 API 추가
2. 엔티티 수정(+사무공간의 부가 정보 컬럼 추가)
> 세부공간이미지 삭제 api 추가, 엔티티 수정(사무공간의 부가 정보 컬럼 추가)

- src/main/java/com/golfzonTech4/worktalk/domain/CustomerComment.java
- src/main/java/com/golfzonTech4/worktalk/domain/QnaComment.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomInsertDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomUpdateDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/room/RoomRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
> room 부가정보 옵션 추가에 따른 dto 수정

- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/SpaceImgDeleteDto.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceImgService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. space, room 이미지 수정, 삭제 로직 수정
> space, room 이미지 수정, 삭제 로직 수정

- build.gradle
- src/main/java/com/golfzonTech4/worktalk/config/RedisConfig.java
- src/main/java/com/golfzonTech4/worktalk/config/SwaggerConfig.java
- src/main/java/com/golfzonTech4/worktalk/controller/RedisController.java
- src/main/java/com/golfzonTech4/worktalk/domain/BookDate.java
- src/main/java/com/golfzonTech4/worktalk/domain/TempRedisReservation.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayInsertDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveCheckDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveTempDto.java
- src/main/java/com/golfzonTech4/worktalk/facade/RedissonFacade.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/redis/TempReservationRedisRepository.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempRedisReservationService.java
1. Rediss 추가 : 예약 임시 데이터 관리를 위한 Rediss 라이브러리 추가
2. Redisson 추가: 동시성 방지를 위한 Redisson 추가
3. Swagger 수정: SpringFox ~ Reddison 충돌로 인한 SpringDoc 라이브러리 추
> [2022-12-16 1st PR] 임시 데이터 관리 관련 Rediss 추가

- src/main/java/com/golfzonTech4/worktalk/config/RedisConfig.java
> [2022-12-16 2nd PR] RedisConfig 설정

- src/main/java/com/golfzonTech4/worktalk/facade/RedissonFacade.java
1. 쓰레드 충돌 시 lock이 안걸리고 unlock이 안되는 문제 발생
> [2022-12-16 3th PR] RedissonFacade 설정

- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomImgDeleteDto.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceImgService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. space, room 이미지 수정, 삭제 로직 수정2
> space, room 이미지 수정, 삭제 로직 수정2

- src/main/java/com/golfzonTech4/worktalk/controller/RedisController.java
- src/main/java/com/golfzonTech4/worktalk/facade/RedissonFacade.java
1. redisson.Rlock -> redisson.semaphore
> [2022-12-16 4th PR] RedissonFacade => Semaphore

- src/main/java/com/golfzonTech4/worktalk/facade/RedissonFacade.java
> [2022-12-16 5th PR] RedissonFacade => RLock

- src/main/java/com/golfzonTech4/worktalk/domain/QnaComment.java
- src/main/java/com/golfzonTech4/worktalk/dto/customercenter/CustomerCenterDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/QnaCommentService.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
1. 1대1문의 삭제로직 에러 수정(Cascade 삭제)
2. 공간 이미지 로직 수정
> 1대1문의, 공간이미지 로직 수정

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReservationController.java
- src/main/java/com/golfzonTech4/worktalk/facade/RedissonFacade.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 회원 관리 기능 중 소셜 로그인 기능 추가로 인하여 쿼리 조회 조건 추가
2. 예약 시 회원의 연락처가 없을 경우 예외 처리 로직 추가
> [2022-12-17 1st PR] 회원 관리 및 예약 기능 개선 

- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
> 예약가능한 날짜, 시간 검색 로직 변경

- src/main/java/com/golfzonTech4/worktalk/controller/QnaController.java
- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Room.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaHostManageDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaSearchDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/room/RoomDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaCommentRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/room/RoomRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/room/RoomRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/QnaService.java
- src/main/java/com/golfzonTech4/worktalk/service/RoomService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 호스트 QnA관리페이지 생성
2. 세부공간 선택 repository 수정
> 호스트 QnA관리페이지 생성, 세부공간 선택 repository 수정

- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempRedisReservationService.java
> [2022-12-19 2nd PR] 예약 내역 조회 매서드 수정

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-19 3rd PR] 예약 내역 조회 매서드 수정 (오타 수정)

- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-19 4th PR] 예약 내역 조회 매서드 수정 쿼리 수정

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-19 5th PR] 예약 결제 가격 검증 로직 수정

- src/main/java/com/golfzonTech4/worktalk/dto/reservation/ReserveSimpleDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
> [2022-12-19 6th PR] 공간ID 기준 예약 리스트 조회 로직 수정

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-19 7th PR] 중복 확인 로직 에러 수정

- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
- src/main/java/com/golfzonTech4/worktalk/service/TempReservationService.java
> [2022-12-19 8th PR] 중복 확인 쿼리 수정

- src/main/java/com/golfzonTech4/worktalk/repository/reservation/ReservationSimpleRepositoryImpl.java
> [2022-12-19 8th PR_2] 중복 확인 쿼리 수정 

- src/main/java/com/golfzonTech4/worktalk/config/RedisConfig.java
- src/main/java/com/golfzonTech4/worktalk/controller/PayController.java
- src/main/java/com/golfzonTech4/worktalk/domain/Mileage_status.java
- src/main/java/com/golfzonTech4/worktalk/dto/pay/PayRoomDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/PayService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
> [2022-12-19 9th PR] 마일리지 로직 수정 

- src/main/java/com/golfzonTech4/worktalk/repository/ListResult.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
> [2022-12-19 10th PR] 마일리지 조회 로직 수정

- src/main/java/com/golfzonTech4/worktalk/service/MileageService.java
- src/main/java/com/golfzonTech4/worktalk/service/PenaltyService.java
1. 결제 취소 시 마일리지 적립 예정 내역이 취소 되도록 수정
2. 매 정각마다 작동되던 페널티 업데이트 로직을 매 자정마다 작동되도록 수정
> [2022-12-20 1st PR] 마일리지 취소 로직 수정 및 페널티 업데이트 로직 수정

- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCenterController.java
- src/main/java/com/golfzonTech4/worktalk/controller/CustomerCommentController.java
- src/main/java/com/golfzonTech4/worktalk/controller/KakaoController.java
- src/main/java/com/golfzonTech4/worktalk/controller/QnaCommentController.java
- src/main/java/com/golfzonTech4/worktalk/controller/QnaController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReviewController.java
- src/main/java/com/golfzonTech4/worktalk/controller/RoomController.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/customercenter/CustomerCenterSearchDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaSearchDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaSpacePagingDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/CustomerCenterService.java
- src/main/java/com/golfzonTech4/worktalk/service/KakaoLoginService.java
- src/main/java/com/golfzonTech4/worktalk/service/QnaService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. Q&A, 1대1문의 페이징
2. 코드 줄정리 및 주석 추가
> 코드 줄정리 및 주석 추가, Q&A, 1대1문의 페이징

- src/main/java/com/golfzonTech4/worktalk/controller/KakaoController.java
> 카카오 로그인 리턴 URL 변경

- src/main/java/com/golfzonTech4/worktalk/repository/mileage/MileageRepositoryImpl.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
1. MemeberService.join => 회원 가입 시 소셜 로그인 여부 입력
2. ReservationService.end => 마일리지 조회 시 쿼리 수정
> [2022-12-21 2nd PR] 예약완료 로직 수정, 회원 가입 로직 수정 

- src/main/java/com/golfzonTech4/worktalk/controller/MemberController.java
- src/main/java/com/golfzonTech4/worktalk/service/MemberService.java
> [2022-12-21 3rd PR] 회원 탈퇴 로직 수정 

- src/main/java/com/golfzonTech4/worktalk/controller/KakaoController.java
- src/main/java/com/golfzonTech4/worktalk/controller/ReviewController.java
- src/main/java/com/golfzonTech4/worktalk/controller/SpaceController.java
- src/main/java/com/golfzonTech4/worktalk/dto/review/ReviewDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/review/ReviewPagingDto.java
- src/main/java/com/golfzonTech4/worktalk/dto/space/HostSpaceDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/review/ReviewRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/repository/review/ReviewRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/room/RoomRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepository.java
- src/main/java/com/golfzonTech4/worktalk/repository/space/SpaceRepositoryCustom.java
- src/main/java/com/golfzonTech4/worktalk/service/KakaoLoginService.java
- src/main/java/com/golfzonTech4/worktalk/service/ReviewService.java
- src/main/java/com/golfzonTech4/worktalk/service/SpaceService.java
1. 카카오 로그인 전화번호 검증 로직
2. 호스트의 후기관리페이지 추가 생성
> 카카오 로그인 전화번호 검증 로직 추가, 호스트의 후기관리페이지

- src/main/java/com/golfzonTech4/worktalk/dto/member/MemberDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/member/MemberRepositoryImpl.java
1. 카카오 로그인 회원일 시 비밀번호 변경을 막기 위한 쿼리문 변경
> [2022-12-21 4th PR] 회원 프로필 로직 수정

- src/main/java/com/golfzonTech4/worktalk/repository/review/ReviewRepositoryCustomImpl.java
> 후기리스트 쿼리 수정

- src/main/java/com/golfzonTech4/worktalk/dto/qna/QnaDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/qna/QnaRepositoryCustomImpl.java
- src/main/java/com/golfzonTech4/worktalk/repository/review/ReviewRepositoryCustomImpl.java
> Q&A 리스트 작성자 출력

- src/main/java/com/golfzonTech4/worktalk/dto/customercenter/CustomerCenterDetailDto.java
- src/main/java/com/golfzonTech4/worktalk/repository/customercenter/CustomerCenterRepositoryCustomImpl.java
> 1대1문의 작성자 출력

- src/main/java/com/golfzonTech4/worktalk/service/ReservationService.java
1. 선결제 중 잔금을 치르지 않은 예약 건에 대하여 적립 예정 마일리지 삭제 적용
> [2022-12-21 5th PR] 예약 노쇼 처리 로직 수정

- src/main/java/com/golfzonTech4/worktalk/repository/pay/PayRepositoryImpl.java
1. 결제 소팅 시 취소된 결제건들을 나오지 않게 수정
> [2022-12-21 6th PR] 결제 소팅 로직 처리

- src/main/java/com/golfzonTech4/worktalk/domain/SpaceImg.java
- src/main/java/com/golfzonTech4/worktalk/service/CustomerCommentService.java
- src/main/java/com/golfzonTech4/worktalk/service/KakaoLoginService.java
- src/main/java/com/golfzonTech4/worktalk/service/QnaCommentService.java
1. 카카오 로그인 수정 완료
2. 불필요한 코드 제거
> 카카오 로그인 수정 완료
